eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('store.urls', namespace='store')),
    path('admin/', admin.site.urls),
]

store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('logout/', views.authenticate_logout, name='logout'),
    path('api/', views.DummyApi.as_view(), name='api'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('login/', views.authenticate_login, name='login'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    first_name = models.CharField(max_length=25, default='')
    last_name = models.CharField(max_length=25, default='')
    email = models.CharField(max_length=100)
    username = models.CharField(max_length=25, help_text='This will be used for your authentication, i-e Login')
    password = models.CharField(max_length=12)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.pk is None:
            User.objects.create_user(email=self.email, password=self.password, username=self.username,
                                     first_name=self.first_name, last_name=self.last_name)
        else:
            User.objects.update(email=self.email, password=self.password, username=self.username,
                                first_name=self.first_name, last_name=self.last_name)
        super(Customer, self).save(force_insert, force_update, using, update_fields)
        try:
            Cart.objects.get(belongs_to=self)
        except Cart.DoesNotExist:
            Cart.objects.create(belongs_to=self)

    def __str__(self):
        if not self.first_name == '' and not self.last_name == '':
            return '{} {}'.format(self.first_name, self.last_name)
        return '{} {}'.format(self.username, self.email)

    def full_name(self):
        if self.first_name == '' and self.last_name == '':
            return ''
        elif self.last_name == '':
            return self.first_name
        elif self.first_name == '':
            return self.last_name

        return '{} {}'.format(self.first_name, self.last_name)


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=150, unique=True)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    price = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return '{}, {}'.format(self.name, self.category.name)

    @property
    def get_price(self):
        return int(self.price)

    @property
    def get_quanitity(self):
        return int(self.quantity)


class Cart(models.Model):
    belongs_to = models.OneToOneField(Customer, on_delete=models.CASCADE, unique=True, null=False)
    item = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return 'Cart of {}'.format(self.belongs_to.full_name())

    def items(self):
        return len(self.item.objects)

store/forms.py
from django import forms
from store.models import Customer


class LoginForm(forms.Form):
    username = forms.CharField(required=True, max_length=25)
    password = forms.CharField(required=True, max_length=12, widget=forms.PasswordInput)


class SignupForm(forms.ModelForm):
    verify_password = forms.CharField(label='Verify Password', widget=forms.PasswordInput())
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'username', 'email', 'password', 'verify_password']
        widgets = {
            'password': forms.PasswordInput()
        }

store/views.py
from django.views.generic import FormView, TemplateView
from django.shortcuts import render
from django.http.response import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from store.forms import LoginForm, SignupForm
from store.models import Customer


@csrf_exempt
def authenticate_login(request):
    if request.method == 'GET':
        return render(request, 'basic.html', {'title': 'Invalid Request!',
                                              'text': 'You cannot access Login with this type of request'})

    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request=request, username=username, password=password)
    if user:
        login(request=request, user=user)
        return HttpResponseRedirect(reverse('store:home'))
    return render(request, 'basic.html', {'title': 'Error', 'text': 'Username or password is incorrect'})

@csrf_exempt
def authenticate_logout(request):
    if request.method == 'GET':
        return render(request, 'basic.html', {'title': 'Invalid Request!',
                                              'text': 'You cannot access Login with this type of request'})

    logout(request)
    return HttpResponseRedirect(reverse('store:home'))


class Home(TemplateView):
    template_name = 'store/home.html'


class Signup(FormView):
    template_name = 'store/signup.html'
    form_class = SignupForm

    def form_valid(self, form):
        customer = Customer(first_name=form.cleaned_data['first_name'],
                            last_name=form.cleaned_data['last_name'],
                            username=form.cleaned_data['username'],
                            email=form.cleaned_data['email'],
                            password=form.cleaned_data['password'])
        customer.save()
        user = User.objects.get(email=customer.email, username=customer.username)
        login(request=self.request, user=user)
        return HttpResponseRedirect(reverse('store:home'))


class DummyApi(APIView):
    def get(self, request):
        name = request.GET.get('name', '')
        response = {
            'name': '{}'.format(name),
            'message': 'Hello there! How are you?'
        }
        return Response(response, status=status.HTTP_200_OK)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_title %}{% endblock %}</title>
    <script
            src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
            crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'script.js' %}"></script>
    {% block scripts %}{% endblock %}
</head>
<body id="{% block body_id %}{% endblock %}">
<header>{% include 'components/header.html' %}</header>
{% include 'components/login-panel.html' %}
<div class="container-fluid">
    {% block content %}

    {% endblock %}
</div>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/basic.html
{% extends 'base.html' %}
{% block page_title %}{{ title }}{% endblock %}
{% block body_id %}basic{% endblock %}
{% block content %}
    <div class="container">
        <span class="heading">{{ title }}</span>
        <span class="body">{{ text }}</span>
    </div>
{% endblock %}

templates/components/footer.html
<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-8"></div>
    </div>
</div>

templates/components/header.html
{% load extras %}
<div class="container-fluid navigation">
    <div class="site-title">
        <span class="title">Gradient</span>
        <span class="caption">An eCommerce site</span>
    </div>
    <div class="authentication">
        {% if not request.user.is_anonymous %}
            <button class="badge" onclick="showTooltip()">{{ request.user|first_letter }}</button>
        {% else %}
            <a class="btn-o" onclick="login()">Login</a> <a class="btn-o" href="{% url 'store:signup' %}">Signup</a>
        {% endif %}
    </div>
    {% if not request.user.is_anonymous %}
        <div class="navigation-tooltip">
            <a href="#" class="tooltip-link">Cart</a>
            <a href="#" class="tooltip-link">Account</a>
            <a href="#" class="tooltip-link">Settings</a>
            <form class="logout" method="post" action="{% url 'store:logout' %}">
                <input type="submit" value="Logout" id="logout">
            </form>
        </div>
    {% endif %}
</div>

templates/components/login-panel.html
<div class="login-panel">
    <div class="login-title">
        <span class="title">Login</span>
        <span class="caption">Enter login details</span>
    </div>
    <form class="login-form" method="post" action="{% url 'store:login' %}">
        <p><label for="id_username">Username:</label> <input type="text" name="username" maxlength="25" required=""
                                                             id="id_username"></p>
        <p><label for="id_password">Password:</label> <input type="password" name="password" maxlength="12"
                                                             required="" id="id_password"></p>
        <input class="btn-c" type="submit" value="Login"> <input class="btn-c" type="reset" value="cancel"
                                                                 onclick="hide()">
    </form>
</div>

templates/store/home.html
{% extends 'base.html' %}
{% block body_id %}home{% endblock %}
{% block page_title %}Home{% endblock %}
{% block content %}

{% endblock %}

templates/store/logout.html
{% extends 'base.html' %}
{% block page_title %}Logout{% endblock %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Logout" class="btn btn-danger">
        <a href="{% url 'store:home' %}">Cancel</a>
    </form>

{% endblock %}

templates/store/signup.html
{% extends 'base.html' %}
{% block body_id %}signup{% endblock %}
{% block content %}
    <div class="signup-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sign-Up"> <input type="reset" value="Cancel">
        </form>
    </div>
{% endblock %}